version: '3'

volumes:
  db-data: {}

services:
  node:
    build: .
    ports:
     - ${web_port}:${web_port}
    volumes:
      - ./:/data
    links:
      - db
    depends_on:
      - db
    env_file: .env
  db:
    image: mariadb
    ports:
      - ${db_port}:3306
    volumes:
      - db-data:/var/lib/mysql
    env_file: .env